
classdef FloatStamped < ros.Message
    %FloatStamped MATLAB implementation of uuv_gazebo_ros_plugins_msgs/FloatStamped
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'uuv_gazebo_ros_plugins_msgs/FloatStamped' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e6c99c37e6f9fe98e071d524cc164e65' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Data' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'data' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Data
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'FloatStamped', 'Header')
            obj.Header = val;
        end
        function set.Data(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'FloatStamped', 'Data');
            obj.Data = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.FloatStamped.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.FloatStamped(strObj);
        end
    end
end
