
classdef GetThrusterStateResponse < ros.Message
    %GetThrusterStateResponse MATLAB implementation of uuv_gazebo_ros_plugins_msgs/GetThrusterStateResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'uuv_gazebo_ros_plugins_msgs/GetThrusterStateResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e2fdda8431274beee70eebaa081c813e' % The MD5 Checksum of the message definition
        PropertyList = { 'IsOn' } % List of non-constant message properties
        ROSPropertyList = { 'is_on' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        IsOn
    end
    methods
        function set.IsOn(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GetThrusterStateResponse', 'IsOn');
            obj.IsOn = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.GetThrusterStateResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.GetThrusterStateResponse(strObj);
        end
    end
end
