
classdef SetThrusterStateRequest < ros.Message
    %SetThrusterStateRequest MATLAB implementation of uuv_gazebo_ros_plugins_msgs/SetThrusterStateRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'uuv_gazebo_ros_plugins_msgs/SetThrusterStateRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '74983d2ffe4877de8ae30b7a94625c41' % The MD5 Checksum of the message definition
        PropertyList = { 'On' } % List of non-constant message properties
        ROSPropertyList = { 'on' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        On
    end
    methods
        function set.On(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetThrusterStateRequest', 'On');
            obj.On = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.SetThrusterStateRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.SetThrusterStateRequest(strObj);
        end
    end
end
