
classdef SetFloatResponse < ros.Message
    %SetFloatResponse MATLAB implementation of uuv_gazebo_ros_plugins_msgs/SetFloatResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'uuv_gazebo_ros_plugins_msgs/SetFloatResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '937c9679a518e3a18d831e57125ea522' % The MD5 Checksum of the message definition
        PropertyList = { 'Success' 'Message' } % List of non-constant message properties
        ROSPropertyList = { 'success' 'message' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Success
        Message
    end
    methods
        function set.Success(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetFloatResponse', 'Success');
            obj.Success = logical(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SetFloatResponse', 'Message');
            obj.Message = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.SetFloatResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.SetFloatResponse(strObj);
        end
    end
end
