
classdef SetUseGlobalCurrentVelRequest < ros.Message
    %SetUseGlobalCurrentVelRequest MATLAB implementation of uuv_gazebo_ros_plugins_msgs/SetUseGlobalCurrentVelRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'uuv_gazebo_ros_plugins_msgs/SetUseGlobalCurrentVelRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'cb3581ad5adb4e1f612596312cf9e4fe' % The MD5 Checksum of the message definition
        PropertyList = { 'UseGlobal' } % List of non-constant message properties
        ROSPropertyList = { 'use_global' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        UseGlobal
    end
    methods
        function set.UseGlobal(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetUseGlobalCurrentVelRequest', 'UseGlobal');
            obj.UseGlobal = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.SetUseGlobalCurrentVelRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.uuv_gazebo_ros_plugins_msgs.SetUseGlobalCurrentVelRequest(strObj);
        end
    end
end
